### ISSUE TITLE
Dataset Availability

### ISSUE THREAD

**Issue by aliinsight** [hobbit-project/DEBS-GC-2018#2]
Hi guys, 
do you intend to provide a complete benchmark dataset of marine traffic for this challenge? If so, by when we should be expecting that it will be available? 

Thanks

**Comment by smirnp** [comment]
Hi! 

The dataset is already prepared, but some formal concerns still left to be solved. 

Hopefully it will be released in couple of days

**Comment by smirnp** [comment]
Please find the training dataset and "how-to-obtain" instructions here: www.cs.otago.ac.nz/debs2018/calls/gc.html.

The training dataset with calculated labels and corrected port's radiuses will be announced in the next couple of days.

**Comment by nduy** [comment]
Thank you for releasing the data. It is said that in order to obtain the password, we need to "send a mail to the organizers stating you agree with the given terms". Who exactly should we contact? 
Vincenzo Gulisano, Zbigniew Jerzak, Pavel Smirnov, Martin Strohbach, Holger Ziekow or Dimitris Zissis.

**Comment by smirnp** [comment]
We are sorry, the requirement to check the agreements was given by provider of the data.
The fastest way is to copy the message to all of the listed people.

**Comment by nduy** [comment]
I understand. Thank you for the response @smirnp.

**Comment by smirnp** [comment]
Not actual anymore.
