### ISSUE TITLE
Question about Pairs evaluated 

### ISSUE THREAD

**Issue by HyungKun** [hobbit-project/DEBS-GC-2018#22]
What exactly does Pairs evaluated mean?

I understand that one tuple comes into the queue and the next tuple comes in if we answer that.

That is, if I received 10000 data and processed 10000 data, I think that all tasks should be sequential and evaluated in order.

When I run an online benchmark, if I set more than 10000 tuple limits, the value of Pairs evaluated will be different from the tuple limit I set. At this time, the average earlyness rate of my system drops considerably.

When I run the experiment locally, I set the tuple limit and the Pairs evaluated to the same value up to 100000.
However, these symptoms only occur online.

What am I missing?

**Comment by smirnp** [comment]
Hi!

> What exactly does Pairs evaluated mean?

pairs evaluated - number of tuples, which was send to benchmarked system. Pairs - because each of the sent tuple are compared with its expected result. Not all 100k tuples may have labels (because of some deviations in data or unfinished trips cutted by tuples limit), so the number of actually sent tuples might be less. It does not depend on the system, but on the data and value of tuples limit.

> That is, if I received 10000 data and processed 10000 data, I think that all tasks should be sequential and evaluated in order.

10000 lines of the dataset file will be taken. Let's consider this is N trips of M ships. Tuples of each of N trips are served sequentally, but M trips from each of M ships are send in parallel in the moment. So you may parallelise and scale your system (example of the distributed sample system will be announced in a couple of days).

> When I run an online benchmark, if I set more than 10000 tuple limits, the value of Pairs evaluated will be different from the tuple limit I set. At this time, the average earlyness rate of my system drops considerably.

Could you please provide me an identifier of you run? I will check if the benchmark correctly cuts the trips.

**Comment by HyungKun** [comment]
I'll give you two numbers for my experiment number.
(1522933815029 - normal, 1522921980645 - abnormal.)

**Comment by HyungKun** [comment]
@smirnp  
Sorry.
I confirmed that it was a problem with my system.
