### ISSUE TITLE
Q2 ranking

### ISSUE THREAD

**Issue by acip** [hobbit-project/DEBS-GC-2018#29]
@smirnp, for Q2 does the port prediction have any influence on it? It is not clear from description if the port prediction is relevant for Q2 -  the descriptions only mentions about the time.

Thank you!

**Comment by smirnp** [comment]
@acip , in fact no. 
Since Q2 accumulates absolute error (in minutes), it is not clear which value should be taken when port name was predicted incorrectly. 
So it was decided to ignore a portName in returned predictions for Q2 during the evaluation. 
In order to fit the returning format you may put everything as portName into a returning tuple.

**Comment by acip** [comment]
Thank you, Pavel!
