### ISSUE TITLE
Paper format for DEBS Grand Challenge

### ISSUE THREAD

**Issue by eonica** [hobbit-project/DEBS-GC-2018#31]
Hello,

Could you please confirm if the 2-page short paper that should be submitted for describing the GC solution should respect the format/templates of the papers in the main research track ( http://www.cs.otago.ac.nz/debs2018/calls/research.html )? Is there any particular detail we should include? 

Also, are we supposed to anonymize the authors as in the research track? I assume not, since the paper should relate with the submitted system anyway. Is that correct or not?

Thank you, 
Emanuel

**Comment by rivetti** [comment]
Hi,
With respect to previous years (4 pages limit), the 2 pages limit is quite short.

We where then also wondering whether
- the paper is intended only for evaluation or is to be written as to be published, ie, can we omit abstract, keywords, challenge and query description, etc, _or_ the paper has to be self-contained thus should include all the above.
- the submission allows appendixes, is there any maximum length recommendation?
- will the camera ready have an increased number of pages ? 

Thanks
Nicolo

**Comment by ziefurt** [comment]
Dear all, 2 pages is the target length for the short paper. You also have an optional appendix to lay out the details of your contribution. There is no limit to the length of the appendix. The paper should allow you to point out strength of your solution that may be independent from the performance (i.e. any original concepts that you have applied). The main purpose is to identify interesting solutions that may not rank among the best in the benchmark. As pointed out in the call, such solutions will also be part of the main session. You do not need to anonymize the paper, because it should be linked to your submitted system.

You do not have to introduce the challenge again - as this can be done by referencing the call – and can focus on the original aspects of your solution. However, we will check if we can reserve more room for the camera ready version. Yet, the time between the notification and the camera ready version will be short (due to the deadline extension).

I hope this clarifies your questions,
Holger
