### ISSUE TITLE
parallel vs sequential task generation

### ISSUE THREAD

**Issue by acip** [hobbit-project/DEBS-GC-2018#33]
Hi @smirnp,

Can you confirm that currently that the task generator is feeding the queue in parallel? We are getting some confusing results.

Thank you!

**Comment by smirnp** [comment]
Hi @acip!  
Could you please provide an id to any of your launches?

**Comment by acip** [comment]
Here are some example: https://master.project-hobbit.eu/experiments/1525113045136,1525108977644,1525108652717,1525108294914,1525108002542,1525107543930

**Comment by acip** [comment]
https://master.project-hobbit.eu/experiments/1524937574198,1525030357724,1524936376651,1524935518543,1524935015463,1524934887936,1524934419308,1524934209927,1525107543930

**Comment by smirnp** [comment]
@acip , initially it sequentally iterates over all available ships and sends out a tuple for each of them. Then it just listens acknowledgements from storage and on each received acknowledge it sends out a new tuple for a acknowledged ship. Do you another situation from a system's side?

**Comment by smirnp** [comment]
Hi @acip , I have investigated the question in detail - your comment is valid - currently evalStorage and dataGenerator are single threaded, while they are expected to serve all ships at the moment. 
I'm preparing that an update and notify you, when multhreaded and multiple generators mode will be available.

**Comment by bdnf** [comment]
@smirnp Hello, Pavel. 
Could you please confirm the final task generation sequence? In the final system, will be the tuples from one TRIP_ID fed sequentially or in parallel from many TRIP_IDs at once?

Thank you!

**Comment by smirnp** [comment]
Hi, @bdnf!
Technically the final run fully repeats the training ones: tuples of a ship fed sequentally, but different ships are served in parallel at the same moment.

**Comment by nduy** [comment]
And TRIP_IDs will not be included in the input stream, right?
BTW, both training and testing phase have disappeared from Hobbit Open Challenges list.

**Comment by smirnp** [comment]
Yes, the TRIP_ID will be excluded. 
The final challenge is hidden from new registrations because of closed deadline.
The training challenge is temporally hidden because of incorrect leaderboards configuration. 
It will be open it since new configuration will be applied. 

For those who have reached the performance limit of a benchmark I have almost finished the multithreaded and multi genenerator version of the benchmark (Find it in benchmark list). 
It sends data from the first training dataset (~500k tuples) and allows to stress your system. You may start using it since the "Under tests" appendix will be removed.

The final run will be performed over x00K  tuples and multithreaded/multigenerator mode will be activated.

**Comment by bdnf** [comment]
@smirnp Thank you!
Both of your answers for mine and @nduy questions were really helpful.

Our team is still waiting for the second training dataset access (e-mail was sent). 
Could you check our request status, please?

**Comment by smirnp** [comment]
@bdnf , please resend the request. Unfortunately I cannot find it in my box.

**Comment by bdnf** [comment]
@smirnp Thanks, I resent it to your e-mail

**Comment by smirnp** [comment]
Hi all!
The leaderboard configurations were updated. Systems are ranked by A1 and A2 respectively.
Leader of the Q2 was not updated during the last challenge round (the platform team is handling the bug now), other systems have been updated as expected.

**Comment by acip** [comment]
Hi Pavel,

Sounds great, but the challenge is not visible at the moment under
https://master.project-hobbit.eu/challenges

**Comment by acip** [comment]
Hi @smirnp ,

I see that the "testing" status was removed from the "DEBS GC 2018 Multithreading Benchmark (SML v2-mt)" benchmark. We have run the a single threaded processing with multiple data generators, but it the experiment errors. 

Here is a reference failed experiment: https://master.project-hobbit.eu/experiments/1526615564615

What is the status of the multi-threading data generation? Anything we should be aware of regarding it?

Thank you!

**Comment by smirnp** [comment]
Hi @acip , 

I have just fixed some troubles, it should work normally now. 

From a system’s point of view nothing should be changed – the throughput of task generators was just increased because of usage of all available resources. With 2-3 generators a benchmarked system should be possible to receive up to 5K tuples per second.

**Comment by smirnp** [comment]
Dear all, I see that with tuplesLimit=0 mt-benchmark stabily hags up after ~520K tuples. 
Please use the limit 100K or 50K as limit for now, I will check the unlimited mode as soon as possible.

**Comment by smirnp** [comment]
I temporally switched off the multithreding, but multiple generators are switched on. The thoughtput should be 2-3K tuples/sec

**Comment by eonica** [comment]
Dear Pavel,

Could you please clarify what is the difference between multithreading and
running with multiple generators?

More precisely, if there are multiple generators, is it guaranteed that
each generator will send tuples associated with a distinct set of ships? (
e.g., if we have two generators is it possible that both generator 1 and
generator 2 send tuples for the same ship in parallel, or not? )

Thank you,
Emanuel

**Comment by smirnp** [comment]
Hi @eonica !

Ships are balanced between generators, so one ship is served only by one data generator instance.

Multithreaded mode means that each dataGenerator may use many threads for serving it's ships instead of one thread. But now multhreading is switched off because: 
a) shows not a much higher performance; 
b) not stable, because ships are not strictly assigned to different threads and sometimes it causes conflicts within some ships

**Comment by acip** [comment]
Hi @smirnp ,

We have noticed that the "DEBS GC 2018 Multithreading Benchmark (SML v2-mt)" Benchmark, run with multiple generators, yields very poor performance. I have created a dummy system (to isolate possible system errors), and the throughput is much slower than the original, single threaded benchmark. The single threaded benchmark we've seen arount 2-2.5K tuples/second.

When can we expect multi-threaded/multi-generators benchmark to work? Or maybe drop this option?

I am asking these as the time is quite short till the deadline and we want to focus our efforts in the right direction.

These are some results with the dummy system, for both bechmarks: https://master.project-hobbit.eu/experiments/1527060124388,1527060128762,1527060138413,1527060142454,1527060162250

Thank you for your time and effort!

NB: the dummy system always reports BARCELONA as destination for Q1 and a dummy date for Q2.
